# Generated by Django 4.2.20 on 2025-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
